[build]
 command: hugo
 commandOrigin: config
 environment:
 - HUGO_VERSION
 - HUGO_ENV
 - HUGO_ENABLEGITINFO
 publish: /opt/build/repo/public
 publishOrigin: config

[context.production.environment]
  HUGO_VERSION = "0.92.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.92.0"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.92.0"

# netlify.toml
# source: https://www.garrickadenbuie.com/blog/blogdown-netlify-new-post-workflow/#netlify-toml
[context.deploy-preview]
command = "hugo -b $DEPLOY_PRIME_URL --buildFuture"

[context.branch-deploy]
command = "hugo -b $DEPLOY_PRIME_URL --buildFuture"
